databases:
  inner:
    host: "127.0.0.1"
    port: 5432
    database: "postgres"
    username: "root"
    password: "temp_pwd1!"
    timezone: "+09:00"

jwt:
  secret_key: "test_secret_key"
  refresh_secret_key: "test_refresh_secret_key"
